title: Minji Jeon
description: Amateur Rocket Engineer
site_title: 'Minji Jeon'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: jmj
blog_url: https://www.jmj.com
email: jminji79@gm.gist.ac.kr
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
